### ISSUE TITLE
when finish fuzz ,10 tombstones about /system/xbin/dexdump for signal 11

### ISSUE THREAD

**Issue by xiaoxiaotu** [antojoseph/droid-ff#4]
when i finish fuzz,there has 10 tombstones about /system/xbin/dexdump for signal 11.
dexdump has something wrong?
--------- beginning of crash
06-07 09:22:22.100 25787 25787 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf6dc0000 in tid 25787 (dexdump)
06-07 09:22:22.203   518   518 F DEBUG   : **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
06-07 09:22:22.203   518   518 F DEBUG   : Build fingerprint: 'unknown'
06-07 09:22:22.203   518   518 F DEBUG   : Revision: '0'
06-07 09:22:22.203   518   518 F DEBUG   : ABI: 'arm'
06-07 09:22:22.203   518   518 F DEBUG   : pid: 25787, tid: 25787, name: dexdump  >>> /system/xbin/dexdump <<<
06-07 09:22:22.204   518   518 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf6dc0000
--------- beginning of system
06-07 09:22:22.204   977  1312 W NativeCrashListener: Couldn't find ProcessRecord for pid 25787
06-07 09:22:22.206   518   518 F DEBUG   :     r0 00004578  r1 f6dbff6c  r2 ffef7ae4  r3 00004578
06-07 09:22:22.206   518   518 E DEBUG   : AM write failed: Broken pipe
06-07 09:22:22.206   518   518 F DEBUG   :     r4 00045780  r5 f6dc001c  r6 0027b8fe  r7 f6dc152c
06-07 09:22:22.206   518   518 F DEBUG   :     r8 80078071  r9 000015af  sl 00000000  fp 00000000
06-07 09:22:22.206   518   518 F DEBUG   :     ip 00000000  sp ff9ec9bc  lr 00000000  pc f7020008  cpsr 20070010
06-07 09:22:22.214   518   518 F DEBUG   :
06-07 09:22:22.214   518   518 F DEBUG   : backtrace:
06-07 09:22:22.214   518   518 F DEBUG   :     #00 pc 00002008  /system/lib/libz.so (adler32+488)
06-07 09:22:22.215   518   518 F DEBUG   :     #01 pc 00007001  /system/xbin/dexdump
06-07 09:22:22.215   518   518 F DEBUG   :     #02 pc 00004081  /system/xbin/dexdump
06-07 09:22:22.215   518   518 F DEBUG   :     #03 pc 00003cf9  /system/xbin/dexdump
06-07 09:22:22.215   518   518 F DEBUG   :     #04 pc 00001ce3  /system/xbin/dexdump
06-07 09:22:22.215   518   518 F DEBUG   :     #05 pc 0001705d  /system/lib/libc.so (__libc_init+44)
06-07 09:22:22.215   518   518 F DEBUG   :     #06 pc 00001dac  /system/xbin/dexdump
06-07 09:22:22.217   529  2766 E DMD     : [M/listen_server] dsm_selinux has error (20901) reported
06-07 09:22:22.217   529  2766 E DMD     : [M/listen_server] action-0, cname-dsm_selinux, info-0
06-07 09:22:22.217   529  2766 E DMD     : [M/dsm_dump_error] dsm_selinux finish dump 226 bytes

**Comment by antojoseph** [comment]
it means that yo have had 10 crashes , you can verify this by manually running the dex file against dexdump manually . its a bug with dexdump .  this is given as an example only , you can target other modules in android and start fuzzing
