### ISSUE TITLE
how to run setup.sh?

### ISSUE THREAD

**Issue by VinothiniNagarajan** [antojoseph/droid-ff#8]

**Comment by antojoseph** [comment]
It's a generic shell script , was there a problem executing this ? If you have trouble with the setup , download  android tamer VM which has the tool pre configured .

**Comment by VinothiniNagarajan** [comment]
Thank you so much,.

**Comment by VinothiniNagarajan** [comment]
How to do with android tamer VM ? Please Can you explain it?

**Comment by antojoseph** [comment]
I could give you a walkthrough in hangouts /skpe if that woks .

**Comment by VinothiniNagarajan** [comment]
Sir, is it working???in Android Tamer?

**Comment by antojoseph** [comment]
Yes . It's available as a menu icon in androir tamer

**Comment by VinothiniNagarajan** [comment]
Sir, May i get ur mail id?or SKype id?

**Comment by antojoseph** [comment]
antojoseph007@gmail.com

**Comment by VinothiniNagarajan** [comment]
Hello sir,

Good morning..

Did u upload that video in youtube??
