### ISSUE TITLE
Please help me for using DroidFF tool

### ISSUE THREAD

**Issue by hongsim-tran** [antojoseph/droid-ff#9]
Dear antojoseph,

I'm trying to use your DroidFF tool but it does not work on my computer.

Problem occurred after I select number of Samples to be Generated. You can see below images for more detail:
With Bit flipper selection:
[https://drive.google.com/file/d/0B7uHDzWwW2yLaVBFa2RDeG5lQTY2dHlHWHA3cnJpSThIUXVv/view?usp=sharing](url)
With Radamsa:
[https://drive.google.com/file/d/0B7uHDzWwW2yLUnQwVnRPOXZUMEJzMUx6aWZPRjV3cGh0U3NN/view?usp=sharing](url)
With Peach:
[https://drive.google.com/file/d/0B7uHDzWwW2yLUlBva25xVkFkUG15MG8yQk1jdUlLY1ZYOVRZ/view?usp=sharing](url)
Please help me to figure out what problem is.

Look forward to your reply soon ^ ^
Thank you so much!

**Comment by antojoseph** [comment]
Hi ,

Please refer to this documentation to help you solve the issue . https://media.defcon.org/DEF%20CON%2024/DEF%20CON%2024%20presentations/DEFCON-24-Anto-Joseph-Fuzzing-Android-Devices.pdf
